### ISSUE TITLE
Confusing code

### ISSUE THREAD

**Issue by ghost** [awsdert/mitsy#1]
file mcc_get.c (line 55 for current master head; c7625b1c92a332476c3c4b30772701b880d8cc12)

```
	if ( size ) {
		if ( addr )	addr = realloc( addr, size );
		else addr = malloc( size );
```
There is no need for this; i.e. if addr is NULL then realloc(addr, size) is the same as realloc(NULL, size) which is perfectly fine and safe (if it's NULL realloc behaves the same as malloc(size)). So, although you'd need to add a temp variable in case realloc() fails I think that overall it would be more readable.

**Comment by awsdert** [comment]
Computer was down for few days so only just seen this, anyways that if statement is there because I actually experienced issues when I initially used just realloc() so that one's gonna stay.
